### ISSUE TITLE
Single Color Bug

### ISSUE THREAD

**Issue by buda1994** [unosquare/ledemotion#41]
When you pick a color, the led strip doesn't show just the selected color, it shows a blurred transition of the color, starting at a lighter color, and ending in the selected color. We still don't know if the problem is a software or a hardware problem.

**Comment by ArCiGo** [comment]
The "Single Color" function is not painting properly some base/selected colors on the led strip

* When a color is selected, this is not painted as it should be (increases its tone according to the size of the strip). This problem is not applicable to primary colors and some secondary colors (colors like orange or yellow presents this problem).
* We made a PoC of the method `EnqueueColor()` to set a full solid color.
* Maybe the problem is related to hardware.
